apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bitbucket.fullname" . }}
  labels:
    app: {{ template "bitbucket.name" . }}
    chart: {{ template "bitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bitbucket.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bitbucket.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: bitbucket-workdir
          emptyDir: {}
        - name: bitbucket-logs
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.image.envs }}
{{ toYaml . | indent 12 }}
            {{- end }}
          volumeMounts:
          - name: bitbucket-workdir
            mountPath: /var/atlassian/application-data/bitbucket
          - name: bitbucket-logs
            mountPath: /opt/atlassian/bitbucket/logs
          ports:
            - name: http
              containerPort: 7990
              protocol: TCP
            - name: ssh
              containerPort: 7999
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
