apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitbucket.fullname" . }}
  labels:
    app: {{ template "bitbucket.name" . }}
    chart: {{ template "bitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: 7990
    - name: git
      protocol: TCP
      port: 7999
      targetPort: {{ .Values.service.sshPort }}
  selector:
    app: {{ template "bitbucket.name" . }}
    release: {{ .Release.Name }}
