# Default values for posteio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: analogic/poste.io
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: posteio
  externalPort:
    # HTTP
    http: 80
    # MAIL
    smtp: 25
    pop3: 110
    imap: 143
    smtps: 465
    msa: 587
    imaps: 993
    pop3s: 995
  internalPort:
    # HTTP
    http: 80
    # MAIL
    smtp: 25
    pop3: 110
    imap: 143
    smtps: 465
    msa: 587
    imaps: 993
    pop3s: 995
  ## List of IP addresses at which the controller services are available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
rbac:
  ## If true, create & use RBAC resources
  #
  create: true
  ## Ignored if rbac.create is true
  #
  serviceAccountName: default
