apiVersion: v1
kind: Service
metadata:
  name: {{ template "confluence.fullname" . }}
  labels:
    app: {{ template "confluence.name" . }}
    chart: {{ template "confluence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: 8090
  selector:
    app: {{ template "confluence.name" . }}
    release: {{ .Release.Name }}
