apiVersion: v1
appVersion: "5.9.1"
description: On-premises source code management for Git that's secure, fast, and enterprise grade.
name: bitbucket
version: 0.0.6
icon: https://ukube.github.io/charts/src/bitbucket/icon.png
