apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "jira.fullname" . }}
  labels:
    app: {{ template "jira.name" . }}
    chart: {{ template "jira.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jira.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jira.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: jira-workdir
          emptyDir: {}
        - name: jira-logs
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value :=  .Values.image.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
          - name: jira-data
            mountPath: /var/atlassian/jira
          - name: jira-logs
            mountPath: /opt/atlassian/jira/logs
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.image.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.livenessProbe.port }}
              scheme: {{ .Values.image.livenessProbe.scheme }}
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 5
          {{- end }}
          {{- if .Values.image.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.readinessProbe.port }}
              scheme: {{ .Values.image.readinessProbe.scheme }}
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          {{- end }}
          resources:
      volumes:
      - name: jira-data
      {{- if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "jira.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{ end }}
      - name: jira-logs
      {{- if .Values.persistence.logs.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "jira.fullname" . }}-logs
      {{- else }}
        emptyDir: {}
      {{ end }}
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
