apiVersion: v1
appVersion: "6.8.1"
description: Confluence is content collaboration software that changes how modern teams work
name: confluence
version: 0.0.2
icon: https://ukube.github.io/charts/src/confluence/icon.png
